application: super-sessions-test
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
# Route handlers
- url: /.*
  script: api.app

libraries:
- name: webapp2
  version: latest

- name: ssl
  version: latest